# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'miracleai.azurecr.io'
  imageRepository: 'miracle-objectdetector-web-test'
  dockerRegistryServiceConnection: 'miracle-docker-repository'

stages:
- stage: Main
  displayName: 
  jobs:  
  - job: BuildAndPushImage
    displayName: Build and push (display)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: '$(containerRegistry)/$(imageRepository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)